version: '2'
services:
    employeeslist-app:
        image: employeeslist
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://employeeslist-postgresql:5432/EmployeesList
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=employeeslist-elasticsearch:9300
        ports:
            - 8080:8080
    employeeslist-postgresql:
        extends:
            file: postgresql.yml
            service: employeeslist-postgresql
    employeeslist-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: employeeslist-elasticsearch
